version: "3.3"

services:
  backend:
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/src/
    links:
      - db
      - redis
    environment:
      - DB_USER=test-api
      - DB_HOST=db
      - DB_DATABASE=test-api
      - DB_PASSWORD=test-api
      - DB_PORT=5432
      - DB_DRIVER=postgresql
      - API_RELOAD=True
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_DEBUG=True
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=test-api
      - POSTGRES_USER=test-api
      - POSTGRES_DB=test-api
  redis:
    image: redis:latest
  go-scraper:
    build: ./go-scraper
    restart: always
    volumes:
      - ./go-scraper/:/app
    links:
      - backend
    environment:
      - API_PORT=8080
      - API_HOST=http://backend
