version: "3.3"

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    links:
      - db
    environment:
      - API_DEBUG=True
      - API_RELOAD=True
      - DB_USER=test-api
      - DB_HOST=db
      - DB_DATABASE=test-api
      - DB_PASSWORD=test-api
      - DB_PORT=5432
      - DB_DRIVER=postgresql
      - API_RELOAD=true
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_DEBUG=true
      - DB_SSL=true
  db:
    image: "postgres:13"
    environment:
      - POSTGRES_PASSWORD=test-api
      - POSTGRES_USER=test-api
      - POSTGRES_DB=test-api
