"""Add hash field to domains

Revision ID: 047e20f1db3c
Revises: 208246967ec0
Create Date: 2021-10-09 21:42:27.924833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047e20f1db3c'
down_revision = '208246967ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('hash', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'hash')
    # ### end Alembic commands ###
