"""rename aktenzeichen -> identifier on ruegen table

Revision ID: 0850e4e07b03
Revises: f4db654a6835
Create Date: 2021-10-10 01:44:19.685167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0850e4e07b03'
down_revision = 'f4db654a6835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('identifier', sa.String(), nullable=False))
    op.drop_constraint('ruegen_aktenzeichen_key', 'ruegen', type_='unique')
    op.create_unique_constraint(None, 'ruegen', ['identifier'])
    op.drop_column('ruegen', 'aktenzeichen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('aktenzeichen', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ruegen', type_='unique')
    op.create_unique_constraint('ruegen_aktenzeichen_key', 'ruegen', ['aktenzeichen'])
    op.drop_column('ruegen', 'identifier')
    # ### end Alembic commands ###
