"""Add basic tables

Revision ID: 208246967ec0
Revises: 25d1ce17df26
Create Date: 2021-10-09 16:06:54.848881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208246967ec0'
down_revision = '25d1ce17df26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fqdn', sa.String(), nullable=False),
    sa.Column('last_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_fqdn'), 'domains', ['fqdn'], unique=True)
    op.create_table('links',
    sa.Column('network', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_index(op.f('ix_domains_fqdn'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
