"""renew layout

Revision ID: 2603a6ae29dc
Revises: 
Create Date: 2021-10-13 21:43:56.635896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2603a6ae29dc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fqdn", sa.String(), nullable=False),
        sa.Column("fqdn_hash", sa.String(length=32), nullable=False),
        sa.Column("last_updated", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fqdn_hash"),
    )
    op.create_index(op.f("ix_domains_fqdn"), "domains", ["fqdn"], unique=True)
    op.create_table(
        "links",
        sa.Column("network", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=False),
        sa.Column("child_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    op.create_table(
        "ruegen",
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("domain_hash", sa.String(length=120), nullable=False),
        sa.Column("ziffer", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_hash"],
            ["domains.fqdn_hash"],
        ),
        sa.PrimaryKeyConstraint("identifier"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_ruegen_domain_hash"), "ruegen", ["domain_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ruegen_domain_hash"), table_name="ruegen")
    op.drop_table("ruegen")
    op.drop_table("links")
    op.drop_index(op.f("ix_domains_fqdn"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
