"""Change hash field to unlimited

Revision ID: 36f375a36286
Revises: 047e20f1db3c
Create Date: 2021-10-09 22:15:53.811678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f375a36286'
down_revision = '047e20f1db3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruegen',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('aktenzeichen', sa.String(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aktenzeichen')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruegen')
    # ### end Alembic commands ###
