"""Fix typo

Revision ID: 59b0eb4ea3b7
Revises: b6f990ccf97d
Create Date: 2021-10-10 10:48:14.452097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b0eb4ea3b7'
down_revision = 'b6f990ccf97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
