"""Add ziffer to ruegen

Revision ID: 5e4c3e6677e7
Revises: d6b592f61073
Create Date: 2021-10-10 10:51:35.391481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4c3e6677e7'
down_revision = 'd6b592f61073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruegen', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
