"""add domain field to ruegen table

Revision ID: a9e58a481ef3
Revises: 3f7082264564
Create Date: 2021-10-10 01:40:40.678705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9e58a481ef3"
down_revision = "3f7082264564"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ruegen", sa.Column("domain", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "ruegen", "domains", ["domain"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ruegen", type_="foreignkey")
    op.drop_column("ruegen", "domain")
    # ### end Alembic commands ###
