"""Fix typo

Revision ID: b6f990ccf97d
Revises: 0850e4e07b03
Create Date: 2021-10-10 10:47:44.189549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f990ccf97d'
down_revision = '0850e4e07b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('ruegen', 'titel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('titel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ruegen', 'title')
    # ### end Alembic commands ###
