"""hange hash field x2

Revision ID: cae261c4805c
Revises: 36f375a36286
Create Date: 2021-10-09 22:20:43.654005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae261c4805c'
down_revision = '36f375a36286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
