"""change identifier structure for ruegen table

Revision ID: d494da800c29
Revises: 5e4c3e6677e7
Create Date: 2021-10-11 20:16:15.737788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd494da800c29'
down_revision = '5e4c3e6677e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'fqdn_hash',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'domains', ['fqdn_hash'])
    op.add_column('ruegen', sa.Column('domain_id', sa.String(length=120), nullable=False))
    op.drop_constraint('ruegen_domain_fkey', 'ruegen', type_='foreignkey')
    op.create_foreign_key(None, 'ruegen', 'domains', ['domain_id'], ['fqdn_hash'])
    op.drop_column('ruegen', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('domain', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ruegen', type_='foreignkey')
    op.create_foreign_key('ruegen_domain_fkey', 'ruegen', 'domains', ['domain'], ['id'])
    op.drop_column('ruegen', 'domain_id')
    op.drop_constraint(None, 'domains', type_='unique')
    op.alter_column('domains', 'fqdn_hash',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
