"""Add ziffer to ruegen

Revision ID: d6b592f61073
Revises: 59b0eb4ea3b7
Create Date: 2021-10-10 10:51:04.587858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b592f61073'
down_revision = '59b0eb4ea3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('ziffer', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruegen', 'ziffer')
    # ### end Alembic commands ###
