"""change primary key for ruege table id -> aktenzeichen

Revision ID: f4db654a6835
Revises: a9e58a481ef3
Create Date: 2021-10-10 01:43:26.165463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4db654a6835'
down_revision = 'a9e58a481ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ruegen', 'domain',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('ruegen', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruegen', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.alter_column('ruegen', 'domain',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
